export const SET_QUESTIONS = "SET_QUESTIONS";
export const GET_CONTESTS = "GET_CONTESTS";
export const SET_CONTEST_QUESTIONS_CODE = "SET_CONTEST_QUESTIONS_CODE";
export const ON_SIGN_UP_CLICK = "ON_SIGN_UP_CLICK";
