export const SET_QUESTIONS = "SET_QUESTIONS";
export const GET_CONTESTS = "GET_CONTESTS";
export const SET_CONTEST_QUESTIONS_CODE = "SET_CONTEST_QUESTIONS_CODE";
export const ON_SIGN_UP_CLICK = "ON_SIGN_UP_CLICK";
export const ON_SIGN_IN_CLICK = "ON_SIGN_IN_CLICK";
export const SET_USER_TO_LOGGED = "SET_USER_TO_LOGGED";
export const SET_JUDGE_DATA = "SET_JUDGE_DATA";
